FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    make \
    curl \
    jq \
    && rm -rf /var/lib/apt/lists/*

RUN git config --system credential.helper store
