#!/usr/bin/env bash
# entrypoint.sh — Main orchestration script for the OAPE PR Lifecycle Agent.
#
# Phases:
#   1. CI monitoring (poll checks, classify failures, post report)
#   2. Failure dispatch (auto-fix, retest, Claude analysis)
#   3. Review handler (address review comments when CI is green)
#   4. Status report
#
# Usage:
#   scripts/pr-agent/entrypoint.sh --mode periodic [--dry-run] [--review]
#   scripts/pr-agent/entrypoint.sh --mode on-demand --pr-url <URL> [--dry-run] [--review]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Source shared guardrail functions
# shellcheck source=scripts/pr-agent/safety.sh
source "${SCRIPT_DIR}/safety.sh"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
PR_AGENT_MAX_PRS="${PR_AGENT_MAX_PRS:-4}"
RATE_LIMIT_SECONDS="${RATE_LIMIT_SECONDS:-60}"
PR_TIMEOUT_SECONDS="${PR_TIMEOUT_SECONDS:-720}"
DRY_RUN="${DRY_RUN:-false}"
MONITOR_ONLY="${MONITOR_ONLY:-false}"
REVIEW_HANDLER_ENABLED="${REVIEW_HANDLER_ENABLED:-false}"
BOT_USER="${BOT_USER:-openshift-app-platform-shift-bot}"
GCSWEB_BASE_URL="${GCSWEB_BASE_URL:-https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com}"
TEAM_REPOS_CSV="${TEAM_REPOS_CSV:-${REPO_ROOT}/config/team-repos.csv}"
if [[ ! -f "$TEAM_REPOS_CSV" && -f /config/team-repos.csv ]]; then
  TEAM_REPOS_CSV="/config/team-repos.csv"
fi
RUNNER_TEMP="${RUNNER_TEMP:-/tmp}"

# Per-PR context (set by parse_pr_url)
OWNER=""
REPO=""
PR_NUMBER=""
CURRENT_PR_URL=""

# Track the PR list file location
PR_LIST_FILE="${RUNNER_TEMP}/pr-agent-pr-list.txt"

# ---------------------------------------------------------------------------
# Crash handler — post error note to PR on unexpected failure
# ---------------------------------------------------------------------------
_cleanup_on_crash() {
  local exit_code=$?
  if [[ $exit_code -ne 0 && -n "$CURRENT_PR_URL" && "$DRY_RUN" != "true" ]]; then
    local marker="<!-- oape-pr-agent-report -->"
    local body
    body="${marker}
## PR Agent Report

**Status:** Agent encountered an error (exit code ${exit_code}).
Check the [CI run](${OAPE_RUN_URL:-https://github.com/${GITHUB_REPOSITORY:-unknown}/actions/runs/${GITHUB_RUN_ID:-${BUILD_ID:-0}}}) for details.

---
*Generated by oape-pr-agent on $(date -u +"%Y-%m-%d %H:%M UTC")*"

    gh pr comment "$PR_NUMBER" --repo "${OWNER}/${REPO}" --body "$body" 2>/dev/null || true
    audit_log "error" "" "" "" "crash handler: exit code ${exit_code}"
  fi
}
trap _cleanup_on_crash EXIT

# ===========================================================================
# Argument Parsing
# ===========================================================================
MODE=""
PR_URL_ARG=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)
      MODE="$2"
      shift 2
      ;;
    --pr-url)
      PR_URL_ARG="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN="true"
      shift
      ;;
    --monitor-only)
      MONITOR_ONLY="true"
      shift
      ;;
    --review)
      REVIEW_HANDLER_ENABLED="true"
      shift
      ;;
    *)
      echo "ERROR: Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if [[ -z "$MODE" ]]; then
  echo "ERROR: --mode is required (periodic or on-demand)" >&2
  exit 1
fi

if [[ "$MODE" == "on-demand" && -z "$PR_URL_ARG" ]]; then
  echo "ERROR: --pr-url is required for on-demand mode" >&2
  exit 1
fi

# ===========================================================================
# Prechecks
# ===========================================================================
run_prechecks() {
  echo "[precheck] Verifying prerequisites..."

  if ! gh auth status &>/dev/null; then
    echo "PRECHECK FAILED: gh CLI is not authenticated (run 'gh auth login')" >&2
    exit 1
  fi

  if [[ -z "${GH_TOKEN:-}" ]]; then
    echo "PRECHECK FAILED: GH_TOKEN environment variable is not set" >&2
    exit 1
  fi

  if [[ ! -f "$TEAM_REPOS_CSV" ]]; then
    echo "PRECHECK FAILED: team-repos.csv not found at ${TEAM_REPOS_CSV}" >&2
    exit 1
  fi

  echo "[precheck] All prechecks passed"
}

# ===========================================================================
# PR URL Parsing
# ===========================================================================
parse_pr_url() {
  local url="$1"
  if [[ "$url" =~ https://github.com/([^/]+)/([^/]+)/pull/([0-9]+) ]]; then
    OWNER="${BASH_REMATCH[1]}"
    REPO="${BASH_REMATCH[2]}"
    PR_NUMBER="${BASH_REMATCH[3]}"
  elif [[ "$url" =~ ^([^/]+)/([^#]+)#([0-9]+)$ ]]; then
    OWNER="${BASH_REMATCH[1]}"
    REPO="${BASH_REMATCH[2]}"
    PR_NUMBER="${BASH_REMATCH[3]}"
  else
    echo "PRECHECK FAILED: Invalid PR URL format: $url" >&2
    return 1
  fi
  CURRENT_PR_URL="https://github.com/${OWNER}/${REPO}/pull/${PR_NUMBER}"
}

# ===========================================================================
# Repo Allowlist Validation
# ===========================================================================
validate_repo_allowed() {
  local owner="$1" repo="$2"
  local target="https://github.com/${owner}/${repo}"

  if ! grep -q "${target}" "$TEAM_REPOS_CSV" 2>/dev/null; then
    # Also check with .git suffix
    if ! grep -q "${target}.git" "$TEAM_REPOS_CSV" 2>/dev/null; then
      echo "PRECHECK FAILED: ${owner}/${repo} is not in the allowed repos list" >&2
      return 1
    fi
  fi
  return 0
}

# ===========================================================================
# PR Discovery (periodic mode)
# ===========================================================================
discover_oape_prs() {
  echo "[discovery] Scanning repos for open PRs..."
  true > "$PR_LIST_FILE"

  local repo_count=0
  local pr_count=0

  {
    read -r  # Skip CSV header
    while IFS=, read -r _product _role repo_url; do
      local owner_repo
      owner_repo=$(echo "$repo_url" | sed 's|https://github.com/||;s|\.git$||')
      repo_count=$((repo_count + 1))

      echo "[discovery] Checking ${owner_repo}..."

      local prs
      if ! prs=$(gh_retry gh pr list --repo "$owner_repo" \
        --state open --json number,url,headRefName,title,labels --limit 20 2>/dev/null); then
        echo "[discovery] WARNING: Failed to list PRs for ${owner_repo}, skipping" >&2
        continue
      fi

      # Filter out PRs with pr-agent:skip label
      prs=$(echo "$prs" | jq -r '[.[] | select(.labels | map(.name) | index("pr-agent:skip") | not)] | .[].url' 2>/dev/null || true)

      while IFS= read -r pr_url; do
        [[ -z "$pr_url" ]] && continue
        echo "$pr_url" >> "$PR_LIST_FILE"
        pr_count=$((pr_count + 1))
      done <<< "$prs"
    done
  } < "$TEAM_REPOS_CSV"

  echo "[discovery] Found ${pr_count} open PR(s) across ${repo_count} repo(s)"
}

# ===========================================================================
# Merge Conflict Detection
# ===========================================================================
check_merge_conflicts() {
  local pr_url="$1"
  local mergeable
  mergeable=$(gh_retry gh pr view "$pr_url" --json mergeable -q .mergeable 2>/dev/null || echo "UNKNOWN")
  if [[ "$mergeable" == "CONFLICTING" ]]; then
    echo "[PR #${PR_NUMBER}] Merge conflict detected — skipping CI analysis and auto-fix"
    return 1
  fi
  return 0
}

# ===========================================================================
# CI Check Monitoring
# ===========================================================================
fetch_ci_status() {
  local owner="$1" repo="$2" pr_number="$3"
  local output_file="${RUNNER_TEMP}/ci-status-${owner}-${repo}-${pr_number}.json"

  # gh pr checks aggregates both GitHub Actions (Checks API) and Prow (Status API)
  if ! gh_retry gh pr checks "$pr_number" --repo "${owner}/${repo}" \
    --json name,state,link,bucket \
    > "$output_file" 2>/dev/null; then
    echo "[]" > "$output_file"
  fi

  local total passed failed pending
  total=$(jq 'length' "$output_file")
  passed=$(jq '[.[] | select(.bucket == "pass")] | length' "$output_file")
  failed=$(jq '[.[] | select(.bucket == "fail")] | length' "$output_file")
  pending=$(jq '[.[] | select(.bucket == "pending")] | length' "$output_file")

  echo "[CI] ${passed}/${total} passed | ${failed} failed | ${pending} pending"
}

aggregate_ci_status() {
  local owner="$1" repo="$2" pr_number="$3"
  local status_file="${RUNNER_TEMP}/ci-status-${owner}-${repo}-${pr_number}.json"

  local total passed failed pending
  total=$(jq 'length' "$status_file")
  passed=$(jq '[.[] | select(.bucket == "pass")] | length' "$status_file")
  failed=$(jq '[.[] | select(.bucket == "fail")] | length' "$status_file")
  pending=$(jq '[.[] | select(.bucket == "pending")] | length' "$status_file")

  if [[ "$total" -eq 0 ]]; then echo "no-checks"
  elif [[ "$failed" -gt 0 ]]; then echo "some-failed"
  elif [[ "$pending" -eq "$total" ]]; then echo "all-pending"
  elif [[ "$pending" -gt 0 ]]; then echo "mixed-pending"
  else echo "all-passed"
  fi
}

# Evaluate only the REQUIRED status checks (per the base branch's protection rules)
# so the review handler waits for required checks to pass without being blocked by
# optional/flaky checks that may stay pending.
# Output: no-checks | required-failed | required-pending | required-passed
# Falls back to requiring ALL reported checks to pass when required-check metadata
# is unavailable (no branch protection or insufficient permission).
required_ci_status() {
  local owner="$1" repo="$2" pr_number="$3"
  local status_file="${RUNNER_TEMP}/ci-status-${owner}-${repo}-${pr_number}.json"

  local total
  total=$(jq 'length' "$status_file")
  if [[ "$total" -eq 0 ]]; then echo "no-checks"; return; fi

  # Fetch the required status-check contexts from the base branch's protection rules.
  local base_branch required_file
  base_branch=$(gh_retry gh pr view "$pr_number" --repo "${owner}/${repo}" \
    --json baseRefName -q .baseRefName 2>/dev/null || echo "")
  required_file="${RUNNER_TEMP}/required-checks-${owner}-${repo}-${pr_number}.json"
  if [[ -z "$base_branch" ]] || ! gh_retry gh api \
      "repos/${owner}/${repo}/branches/${base_branch}/protection/required_status_checks" \
      --jq '[.contexts[]?, (.checks[]?.context)] | unique' > "$required_file" 2>/dev/null; then
    echo "[]" > "$required_file"
  fi

  local required_count
  required_count=$(jq 'length' "$required_file" 2>/dev/null || echo 0)

  if [[ "$required_count" -eq 0 ]]; then
    # No required-check info — fall back to requiring ALL checks to be green.
    local failed pending
    failed=$(jq '[.[] | select(.bucket == "fail")] | length' "$status_file")
    pending=$(jq '[.[] | select(.bucket == "pending")] | length' "$status_file")
    if [[ "$failed" -gt 0 ]]; then echo "required-failed"
    elif [[ "$pending" -gt 0 ]]; then echo "required-pending"
    else echo "required-passed"
    fi
    return
  fi

  # Evaluate only the checks whose name matches a required context. gh's bucket is
  # one of: pass | fail | pending | skipping | cancel. A skipped required check does
  # not block merge (GitHub treats it as success), so count it as passed; a cancelled
  # one is non-passing, so count it as failed. Anything left unclassified here would
  # under-count `reported` below and pin the status at required-pending forever.
  local req_failed req_pending req_passed
  req_failed=$(jq --slurpfile req "$required_file" \
    '[.[] | select(.name as $n | ($req[0] | index($n)) != null) | select(.bucket == "fail" or .bucket == "cancel")] | length' "$status_file")
  req_pending=$(jq --slurpfile req "$required_file" \
    '[.[] | select(.name as $n | ($req[0] | index($n)) != null) | select(.bucket == "pending")] | length' "$status_file")
  req_passed=$(jq --slurpfile req "$required_file" \
    '[.[] | select(.name as $n | ($req[0] | index($n)) != null) | select(.bucket == "pass" or .bucket == "skipping")] | length' "$status_file")

  # A required context that has not reported any status yet counts as pending (this
  # matches GitHub, which blocks merge until every required check reports).
  local reported=$((req_failed + req_pending + req_passed))
  if [[ "$req_failed" -gt 0 ]]; then echo "required-failed"
  elif [[ "$req_pending" -gt 0 || "$reported" -lt "$required_count" ]]; then echo "required-pending"
  else echo "required-passed"
  fi
}

# ===========================================================================
# Failure Log Fetching
# ===========================================================================
fetch_failure_logs() {
  local owner="$1" repo="$2" pr_number="$3"
  local status_file="${RUNNER_TEMP}/ci-status-${owner}-${repo}-${pr_number}.json"

  jq -r '.[] | select(.bucket == "fail") | "\(.name)\t\(.link)"' "$status_file" \
    | while IFS=$'\t' read -r check_name url; do
    [[ -z "$url" ]] && continue

    local log_id
    log_id=$(echo "$check_name" | tr '/ ' '__')

    if [[ "$url" == *"github.com"*"/actions/"* ]]; then
      # GitHub Actions: extract run ID, fetch failed step logs
      local run_id
      run_id=$(echo "$url" | grep -oP 'runs/\K[0-9]+' || true)
      if [[ -n "$run_id" ]]; then
        gh_retry gh run view "$run_id" --repo "${owner}/${repo}" --log-failed \
          > "${RUNNER_TEMP}/log-${log_id}.txt" 2>/dev/null || true
      fi
    elif [[ "$url" == *"prow"* ]]; then
      # Prow: extract GCS path from the prow UI URL and fetch build-log.txt
      local gcs_path
      gcs_path=$(echo "$url" | sed -n 's|.*/view/g[cs]s\?/||p')
      if [[ -n "$gcs_path" ]]; then
        local gcsweb_url="${GCSWEB_BASE_URL}/gcs/${gcs_path}/build-log.txt"
        curl -sSL "$gcsweb_url" 2>/dev/null | tail -1000 \
          > "${RUNNER_TEMP}/log-${log_id}.txt" 2>/dev/null || true
      fi
    fi
  done
}

# ===========================================================================
# Deterministic Failure Classification (regex-based, no Claude API)
# ===========================================================================
classify_failure_deterministic() {
  local log_file="$1"

  if [[ ! -s "$log_file" ]]; then
    echo "unknown"
    return
  fi

  local content
  content=$(cat "$log_file")

  if echo "$content" | grep -qiE -- 'gofmt|goimports|formatting differs|diff.*\.go'; then
    echo "trivial-format"
  elif echo "$content" | grep -qiE -- 'imported and not used|could not import|import ordering'; then
    echo "trivial-import"
  elif echo "$content" | grep -qiE -- 'golangci-lint|golint|staticcheck|revive'; then
    echo "trivial-lint"
  elif echo "$content" | grep -qiE -- 'generated code is out of date|make generate|make manifests|deepcopy-gen|zz_generated'; then
    echo "trivial-generated-files"
  elif echo "$content" | grep -qiE -- 'cannot compile|undefined:|syntax error|cannot use.*as.*in'; then
    echo "build-error"
  elif echo "$content" | grep -qiE -- '--- FAIL|FAIL\s|panic:.*test|assertion failed'; then
    echo "test-failure"
  elif echo "$content" | grep -qiE -- 'context deadline exceeded|connection refused|i/o timeout|ErrImagePull|pod sandbox|TLS handshake timeout'; then
    echo "infra-flake"
  else
    echo "unknown"
  fi
}

classify_all_failures() {
  local owner="$1" repo="$2" pr_number="$3"
  local analysis_file="${RUNNER_TEMP}/failure-analysis-${owner}-${repo}-${pr_number}.json"
  local results="[]"

  for log_file in "${RUNNER_TEMP}"/log-*.txt; do
    [[ -f "$log_file" ]] || continue

    local log_name
    log_name=$(basename "$log_file" .txt | sed 's/^log-//')

    local category
    category=$(classify_failure_deterministic "$log_file")

    results=$(echo "$results" | jq \
      --arg cat "$category" \
      --arg name "$log_name" \
      --arg file "$log_file" \
      '. + [{"category": $cat, "confidence": "high", "check_name": $name, "log_file": $file, "root_cause": $cat, "suggested_fix": ""}]')
  done

  echo "$results" > "$analysis_file"
  local trivial_count
  trivial_count=$(echo "$results" | jq '[.[] | select(.category | startswith("trivial-"))] | length')
  local total_count
  total_count=$(echo "$results" | jq 'length')
  echo "[classify] ${trivial_count}/${total_count} failures are trivially fixable"
}

# ===========================================================================
# Auto-Fix Engine (Phase 1: trivial-format + trivial-generated-files only)
# ===========================================================================
apply_trivial_fixes() {
  local owner="$1" repo="$2" pr_number="$3"
  local analysis_file="${RUNNER_TEMP}/failure-analysis-${owner}-${repo}-${pr_number}.json"

  if [[ ! -f "$analysis_file" ]]; then
    echo "[auto-fix] No failure analysis found, skipping"
    return 0
  fi

  local fixable
  fixable=$(jq -c '[.[] | select(.category == "trivial-format" or .category == "trivial-generated-files")]' "$analysis_file")
  local fix_count
  fix_count=$(echo "$fixable" | jq 'length')

  if [[ "$fix_count" -eq 0 ]]; then
    echo "[auto-fix] No trivially fixable failures found"
    return 0
  fi

  echo "[auto-fix] Found ${fix_count} fixable failure(s), cloning repo..."

  # Clone with blobless filter for performance
  local workdir="${RUNNER_TEMP}/repo-${owner}-${repo}-${pr_number}"
  if [[ -d "$workdir" ]]; then
    rm -rf "$workdir"
  fi

  if ! gh_retry gh repo clone "${owner}/${repo}" "$workdir" -- --filter=blob:none --single-branch 2>/dev/null; then
    echo "[auto-fix] ERROR: Failed to clone ${owner}/${repo}" >&2
    audit_log "error" "" "" "" "clone failed for ${owner}/${repo}"
    return 1
  fi

  cd "$workdir"

  if ! gh pr checkout "$pr_number" 2>/dev/null; then
    echo "[auto-fix] ERROR: Failed to checkout PR #${pr_number}" >&2
    audit_log "error" "" "" "" "checkout failed for PR #${pr_number}"
    cd "$REPO_ROOT"
    return 1
  fi

  # Configure git identity for the bot
  git config user.name "$BOT_USER"
  git config user.email "267347085+${BOT_USER}@users.noreply.github.com"
  git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${owner}/${repo}.git"

  # Determine PR base branch for scoping fixes
  local base_branch
  base_branch=$(gh pr view "$pr_number" --repo "${owner}/${repo}" --json baseRefName -q .baseRefName 2>/dev/null || echo "main")
  git fetch origin "${base_branch}" --depth=1 2>/dev/null || true

  local pr_commit_count=0

  echo "$fixable" | jq -c '.[]' | while IFS= read -r fix; do
    local category
    category=$(echo "$fix" | jq -r '.category')

    # Check global commit limits
    if ! check_commit_limit "$pr_commit_count"; then
      audit_log "skipped" "$category" "" "" "commit limit reached"
      continue
    fi

    echo "[auto-fix] Applying fix for: ${category}"

    case "$category" in
      trivial-format)
        # Scope go fmt to only PR-changed Go files
        local changed_go_files
        changed_go_files=$(git diff --name-only "origin/${base_branch}" -- '*.go' 2>/dev/null || true)
        if [[ -n "$changed_go_files" ]]; then
          echo "$changed_go_files" | xargs -r go fmt 2>/dev/null || true
          if command -v goimports &>/dev/null; then
            echo "$changed_go_files" | xargs -r goimports -w 2>/dev/null || true
          fi
        fi
        ;;
      trivial-generated-files)
        # Framework-aware generation
        if [[ -f go.mod ]] && grep -q 'sigs.k8s.io/controller-runtime' go.mod; then
          make generate 2>/dev/null || true
          make manifests 2>/dev/null || true
        elif [[ -f go.mod ]] && grep -q 'github.com/openshift/library-go' go.mod; then
          make update 2>/dev/null || true
        else
          make generate 2>/dev/null || make update 2>/dev/null || true
        fi
        ;;
      *)
        echo "[auto-fix] Skipping unsupported category: ${category}"
        continue
        ;;
    esac

    # Check if there are actual changes
    local modified_files
    modified_files=$(git diff --name-only; git ls-files --others --exclude-standard)
    if [[ -z "$modified_files" ]]; then
      echo "[auto-fix] No changes after applying ${category} fix"
      continue
    fi

    # Pre-commit blocklist check on actual modified files
    if ! check_blocklist "$modified_files" "$category"; then
      echo "[auto-fix] Blocklist violation on modified files, reverting"
      git checkout -- . 2>/dev/null || true
      git clean -fd 2>/dev/null || true
      audit_log "reverted" "$category" "$modified_files" "" "post-fix blocklist violation"
      continue
    fi

    # Diff size guard
    if ! check_diff_size; then
      git checkout -- . 2>/dev/null || true
      git clean -fd 2>/dev/null || true
      audit_log "reverted" "$category" "$modified_files" "" "diff too large"
      continue
    fi

    # Verify fix compiles
    if ! go build ./... 2>/dev/null; then
      echo "[auto-fix] Fix broke compilation, reverting"
      git checkout -- . 2>/dev/null || true
      git clean -fd 2>/dev/null || true
      audit_log "reverted" "$category" "$modified_files" "" "fix broke compilation"
      continue
    fi

    if ! go vet ./... 2>/dev/null; then
      echo "[auto-fix] Fix failed go vet, reverting"
      git checkout -- . 2>/dev/null || true
      git clean -fd 2>/dev/null || true
      audit_log "reverted" "$category" "$modified_files" "" "fix failed go vet"
      continue
    fi

    if [[ "$DRY_RUN" == "true" ]]; then
      echo "[auto-fix] DRY RUN: Would commit and push fix for ${category}"
      audit_log "dry-run" "$category" "$modified_files" "" "would commit and push"
      git checkout -- . 2>/dev/null || true
      git clean -fd 2>/dev/null || true
      continue
    fi

    # Stage all changes (tracked + untracked)
    git diff --name-only -z | xargs -0 -r git add
    git ls-files --others --exclude-standard -z | xargs -0 -r git add
    git commit -m "fix: ${category} — auto-fix by oape-pr-agent"
    local sha
    sha=$(git rev-parse HEAD)

    # Pull before push to handle concurrent pushes
    if ! git pull --rebase origin HEAD 2>/dev/null; then
      git rebase --abort 2>/dev/null || true
      audit_log "reverted" "$category" "$modified_files" "$sha" "rebase conflict — concurrent push detected"
      git reset --hard HEAD~1 2>/dev/null || true
      continue
    fi

    git push origin HEAD
    pr_commit_count=$((pr_commit_count + 1))
    increment_commit_count > /dev/null

    audit_log "auto-fix" "$category" "$modified_files" "$sha" "success"
    echo "[auto-fix] Pushed fix: ${sha} (${category})"
  done

  cd "$REPO_ROOT"
}

# ===========================================================================
# State Persistence (embedded in PR comment)
# ===========================================================================
load_persisted_state() {
  local owner="$1" repo="$2" pr_number="$3"
  local state_file="${RUNNER_TEMP}/pr-agent-state-${owner}-${repo}-${pr_number}.json"

  # Default empty state
  if [[ ! -f "$state_file" ]]; then
    echo '{"analyzed":[],"addressed":[],"last_run":""}' > "$state_file"
  fi

  # Try to load state from existing PR comment
  local marker="<!-- oape-pr-agent-report -->"
  local existing_body
  existing_body=$(gh api "repos/${owner}/${repo}/issues/${pr_number}/comments" \
    --jq ".[] | select(.body | contains(\"${marker}\")) | .body" 2>/dev/null | head -1 || true)

  if [[ -n "$existing_body" ]]; then
    local persisted_state
    persisted_state=$(echo "$existing_body" | grep -oP '(?<=oape-pr-agent-state:)[A-Za-z0-9+/=]+' | head -1 || true)
    if [[ -n "$persisted_state" ]]; then
      echo "$persisted_state" | base64 -d > "$state_file" 2>/dev/null || true
    fi
  fi
}

save_persisted_state() {
  local owner="$1" repo="$2" pr_number="$3"
  local state_file="${RUNNER_TEMP}/pr-agent-state-${owner}-${repo}-${pr_number}.json"

  # Update last_run timestamp
  local current_state
  current_state=$(cat "$state_file" 2>/dev/null || echo '{"analyzed":[],"addressed":[],"last_run":""}')
  echo "$current_state" | jq --arg ts "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" '.last_run = $ts' > "$state_file"
}

# ===========================================================================
# Status Report Generation
# ===========================================================================
generate_status_report() {
  local owner="$1" repo="$2" pr_number="$3"
  local report_file="${RUNNER_TEMP}/pr-agent-report-${owner}-${repo}-${pr_number}.md"
  local ci_file="${RUNNER_TEMP}/ci-status-${owner}-${repo}-${pr_number}.json"
  local analysis_file="${RUNNER_TEMP}/failure-analysis-${owner}-${repo}-${pr_number}.json"
  local merge_conflict="${4:-false}"

  # Fetch PR metadata
  local pr_info
  pr_info=$(gh_retry gh pr view "$pr_number" --repo "${owner}/${repo}" \
    --json title,url,headRefName,baseRefName -q '.' 2>/dev/null || echo '{}')

  local title head base pr_url_display
  title=$(echo "$pr_info" | jq -r '.title // "unknown"')
  head=$(echo "$pr_info" | jq -r '.headRefName // "unknown"')
  base=$(echo "$pr_info" | jq -r '.baseRefName // "unknown"')
  pr_url_display="https://github.com/${owner}/${repo}/pull/${pr_number}"

  local run_link="${OAPE_RUN_URL:-https://github.com/${GITHUB_REPOSITORY:-unknown}/actions/runs/${GITHUB_RUN_ID:-${BUILD_ID:-0}}}"
  local mode_label="${MODE:-periodic}"
  local dry_run_banner=""
  if [[ "$DRY_RUN" == "true" ]]; then
    dry_run_banner="**DRY RUN** — no changes were made

"
  fi

  # CI stats
  local passed=0 failed=0 pending=0 total=0
  if [[ -f "$ci_file" ]]; then
    total=$(jq 'length' "$ci_file" 2>/dev/null || echo 0)
    passed=$(jq '[.[] | select(.bucket == "pass")] | length' "$ci_file" 2>/dev/null || echo 0)
    failed=$(jq '[.[] | select(.bucket == "fail")] | length' "$ci_file" 2>/dev/null || echo 0)
    pending=$(jq '[.[] | select(.bucket == "pending")] | length' "$ci_file" 2>/dev/null || echo 0)
  fi

  # Build report
  {
    echo "## PR Agent Report: ${REPO}#${pr_number}"
    echo ""
    echo "**PR:** [${title}](${pr_url_display})"
    echo "**Branch:** \`${head}\` → \`${base}\`"
    echo "**Run:** [#${GITHUB_RUN_ID:-${BUILD_ID:-N/A}}](${run_link})"
    echo "**Mode:** ${mode_label}"
    echo ""
    echo "${dry_run_banner}"

    # Merge conflict section
    if [[ "$merge_conflict" == "true" ]]; then
      echo "### Merge Conflict"
      echo ""
      echo "> **This PR has merge conflicts.** Please rebase or merge the base branch to resolve conflicts before the agent can analyze CI failures or apply fixes."
      echo ""
    fi

    # CI check results
    echo "### CI Check Results"
    echo ""
    echo "| Status | Count |"
    echo "|--------|-------|"
    echo "| Passed | ${passed} |"
    echo "| Failed | ${failed} |"
    echo "| Pending | ${pending} |"
    echo ""

    if [[ "$merge_conflict" != "true" && -f "$ci_file" && "$failed" -gt 0 ]]; then
      echo "<details>"
      echo "<summary>Failed checks (${failed})</summary>"
      echo ""
      echo "| Check | Link |"
      echo "|-------|------|"
      jq -r '.[] | select(.bucket == "fail") | "| \(.name) | [\(.name)](\(.link)) |"' "$ci_file" 2>/dev/null || true
      echo ""
      echo "</details>"
      echo ""
    fi

    # Fixes applied
    echo "### Fixes Applied"
    echo ""
    local fix_entries
    fix_entries=$(grep '"action":"auto-fix"' "$AUDIT_LOG" 2>/dev/null || true)
    if [[ -n "$fix_entries" ]]; then
      echo "$fix_entries" | while IFS= read -r entry; do
        local commit category outcome
        commit=$(echo "$entry" | jq -r '.commit')
        category=$(echo "$entry" | jq -r '.type')
        outcome=$(echo "$entry" | jq -r '.outcome')
        echo "- [\`${commit:0:7}\`](https://github.com/${owner}/${repo}/commit/${commit}) — \`${category}\`: ${outcome}"
      done
    else
      echo "- (none)"
    fi
    echo ""

    # Infrastructure flakes
    if [[ -f "$analysis_file" ]]; then
      local flake_count
      flake_count=$(jq '[.[] | select(.category == "infra-flake")] | length' "$analysis_file" 2>/dev/null || echo 0)
      if [[ "$flake_count" -gt 0 ]]; then
        echo "### Infrastructure Flakes"
        echo ""
        echo "The following CI jobs appear to be infrastructure flakes (timeouts, network errors) rather than code issues:"
        echo ""
        jq -r '.[] | select(.category == "infra-flake") | "- \(.check_name)"' "$analysis_file" 2>/dev/null || true
        echo ""
      fi
    fi

    # Remaining issues
    echo "### Remaining Issues"
    echo ""
    local blocked_entries
    blocked_entries=$(grep -E '"action":"(blocked|skipped|reverted)"' "$AUDIT_LOG" 2>/dev/null || true)
    if [[ -n "$blocked_entries" ]]; then
      echo "$blocked_entries" | while IFS= read -r entry; do
        local category outcome
        category=$(echo "$entry" | jq -r '.type')
        outcome=$(echo "$entry" | jq -r '.outcome')
        echo "- \`${category}\`: ${outcome}"
      done
    fi

    # Non-trivial failures
    if [[ -f "$analysis_file" ]]; then
      local non_trivial
      non_trivial=$(jq -r '.[] | select(.category == "build-error" or .category == "test-failure" or .category == "unknown") | "- `\(.category)`: \(.check_name)"' "$analysis_file" 2>/dev/null || true)
      if [[ -n "$non_trivial" ]]; then
        echo ""
        echo "**Requires human attention:**"
        echo "$non_trivial"
      fi
    fi

    if [[ -z "$blocked_entries" ]] && { [[ ! -f "$analysis_file" ]] || [[ $(jq '[.[] | select(.category == "build-error" or .category == "test-failure" or .category == "unknown")] | length' "$analysis_file" 2>/dev/null || echo 0) -eq 0 ]]; }; then
      echo "- (none)"
    fi
    echo ""

    # Run summary
    echo "### Run Summary"
    echo ""
    local total_commits
    total_commits=$(cat "$COMMIT_COUNTER_FILE" 2>/dev/null || echo 0)
    echo "- **Commits this run:** ${total_commits}"
    echo "- **Classification:** deterministic (regex-based)"
    echo ""

    echo "---"
    echo "*Generated by oape-pr-agent on $(date -u +"%Y-%m-%d %H:%M UTC")*"
  } > "$report_file"
}

# ===========================================================================
# Post Report as PR Comment (update if exists)
# ===========================================================================
post_status_comment() {
  local owner="$1" repo="$2" pr_number="$3"
  local report_file="${RUNNER_TEMP}/pr-agent-report-${owner}-${repo}-${pr_number}.md"
  local state_file="${RUNNER_TEMP}/pr-agent-state-${owner}-${repo}-${pr_number}.json"
  local marker="<!-- oape-pr-agent-report -->"

  if [[ ! -f "$report_file" ]]; then
    echo "[report] No report file found, skipping comment" >&2
    return 0
  fi

  # Embed state in the comment for cross-run persistence
  local state_block=""
  if [[ -f "$state_file" ]]; then
    local state_b64
    state_b64=$(base64 -w0 < "$state_file")
    state_block="<!-- oape-pr-agent-state:${state_b64} -->"
  fi

  local body
  body="${marker}
${state_block}
$(cat "$report_file")"

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "[report] DRY RUN: Would post/update report comment on ${owner}/${repo}#${pr_number}"
    audit_log "dry-run" "report" "" "" "would post PR comment"
    return 0
  fi

  if [[ "${POST_PR_COMMENT:-true}" != "true" ]]; then
    echo "[report] POST_PR_COMMENT=false — skipping PR comment (report in ${report_file})"
    return 0
  fi

  # Check for existing agent comment
  local existing_comment_id
  existing_comment_id=$(gh api "repos/${owner}/${repo}/issues/${pr_number}/comments" \
    --jq ".[] | select(.body | contains(\"${marker}\")) | .id" 2>/dev/null | head -1 || true)

  if [[ -n "$existing_comment_id" ]]; then
    gh_retry gh api "repos/${owner}/${repo}/issues/comments/${existing_comment_id}" \
      -X PATCH -f body="$body" > /dev/null 2>&1
    echo "[report] Updated existing report comment on ${owner}/${repo}#${pr_number}"
  else
    gh_retry gh pr comment "$pr_number" --repo "${owner}/${repo}" --body "$body" > /dev/null 2>&1
    echo "[report] Posted new report comment on ${owner}/${repo}#${pr_number}"
  fi
}

# ===========================================================================
# PR Processing Pipeline
# ===========================================================================
process_pr() {
  local pr_url="$1"
  parse_pr_url "$pr_url"
  CURRENT_PR_URL="$pr_url"

  echo "[PR #${PR_NUMBER}] ${OWNER}/${REPO}#${PR_NUMBER} — processing started"

  # Load persisted state from previous runs
  load_persisted_state "$OWNER" "$REPO" "$PR_NUMBER"

  # Phase 0: Validate PR is open
  local pr_state
  pr_state=$(gh_retry gh pr view "$pr_url" --json state -q .state 2>/dev/null || echo "UNKNOWN")
  if [[ "$pr_state" != "OPEN" ]]; then
    echo "[PR #${PR_NUMBER}] PR is not open (state: ${pr_state}), skipping"
    return 0
  fi

  # Phase 0b: Merge conflict check
  if ! check_merge_conflicts "$pr_url"; then
    generate_status_report "$OWNER" "$REPO" "$PR_NUMBER" "true"
    post_status_comment "$OWNER" "$REPO" "$PR_NUMBER"
    save_persisted_state "$OWNER" "$REPO" "$PR_NUMBER"
    echo "[PR #${PR_NUMBER}] ${OWNER}/${REPO}#${PR_NUMBER} — processing complete (merge conflict)"
    return 0
  fi

  # Phase 1: CI Check Monitoring
  echo "[PR #${PR_NUMBER}] Phase: CI monitoring — started"
  fetch_ci_status "$OWNER" "$REPO" "$PR_NUMBER"
  local ci_status
  ci_status=$(aggregate_ci_status "$OWNER" "$REPO" "$PR_NUMBER")
  echo "[PR #${PR_NUMBER}] Phase: CI monitoring — completed (status: ${ci_status})"

  # Phase 2: Failure Analysis + Auto-Fix (only if there are failures)
  if [[ "$ci_status" == "some-failed" ]]; then
    echo "[PR #${PR_NUMBER}] Phase: failure analysis — started"
    fetch_failure_logs "$OWNER" "$REPO" "$PR_NUMBER"
    classify_all_failures "$OWNER" "$REPO" "$PR_NUMBER"
    echo "[PR #${PR_NUMBER}] Phase: failure analysis — completed"

    if [[ "$MONITOR_ONLY" != "true" ]]; then
      echo "[PR #${PR_NUMBER}] Phase: auto-fix — started"
      apply_trivial_fixes "$OWNER" "$REPO" "$PR_NUMBER" || true
      echo "[PR #${PR_NUMBER}] Phase: auto-fix — completed"
    else
      echo "[PR #${PR_NUMBER}] Phase: auto-fix — skipped (monitor-only mode)"
    fi
  fi

  # Phase 3: Review Handler (only when all REQUIRED CI checks are green and enabled).
  # Skip the required-CI evaluation entirely when the handler cannot run — it makes two
  # extra gh API calls (pr view + branch protection) whose result would be discarded.
  if [[ "$REVIEW_HANDLER_ENABLED" == "true" && "$MONITOR_ONLY" != "true" ]]; then
    local required_status
    required_status=$(required_ci_status "$OWNER" "$REPO" "$PR_NUMBER")
    echo "[PR #${PR_NUMBER}] Required CI status: ${required_status}"
    if [[ "$required_status" == "required-passed" ]]; then
      echo "[PR #${PR_NUMBER}] Phase: review handler — started"
      local review_handler="${SCRIPT_DIR}/review-handler.sh"
      if [[ -x "$review_handler" ]]; then
        local review_args=(--pr-url "https://github.com/${OWNER}/${REPO}/pull/${PR_NUMBER}")
        if [[ "$DRY_RUN" == "true" ]]; then
          review_args+=(--dry-run)
        fi
        "$review_handler" "${review_args[@]}" || {
          echo "[PR #${PR_NUMBER}] Phase: review handler — exited with $? (non-fatal)"
        }
      else
        echo "[PR #${PR_NUMBER}] Phase: review handler — skipped (script not found)"
      fi
      echo "[PR #${PR_NUMBER}] Phase: review handler — completed"
    else
      echo "[PR #${PR_NUMBER}] Phase: review handler — skipped (waiting for required CI: ${required_status})"
    fi
  else
    echo "[PR #${PR_NUMBER}] Phase: review handler — skipped (disabled or monitor-only)"
  fi

  # Phase 4: Status Report
  echo "[PR #${PR_NUMBER}] Phase: status report — started"
  generate_status_report "$OWNER" "$REPO" "$PR_NUMBER"
  post_status_comment "$OWNER" "$REPO" "$PR_NUMBER"
  save_persisted_state "$OWNER" "$REPO" "$PR_NUMBER"
  echo "[PR #${PR_NUMBER}] Phase: status report — completed"

  # Clean up log files for this PR to avoid polluting the next PR
  rm -f "${RUNNER_TEMP}"/log-*.txt

  echo "[PR #${PR_NUMBER}] ${OWNER}/${REPO}#${PR_NUMBER} — processing complete"
}

# ===========================================================================
# Timeout Report — posted when per-PR timeout fires
# ===========================================================================
_post_timeout_report() {
  local owner="$1" repo="$2" pr_number="$3"
  local marker="<!-- oape-pr-agent-report -->"
  local body
  body="${marker}
## PR Agent Report: ${repo}#${pr_number}

**Status:** Timed out after ${PR_TIMEOUT_SECONDS}s. The agent could not complete analysis within the per-PR time limit.

A partial analysis may be available in the [CI run](${OAPE_RUN_URL:-N/A}) logs.

---
*Generated by oape-pr-agent on $(date -u +"%Y-%m-%d %H:%M UTC")*"

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "[timeout] DRY RUN: Would post timeout report on ${owner}/${repo}#${pr_number}"
    return 0
  fi

  local existing_comment_id
  existing_comment_id=$(gh api "repos/${owner}/${repo}/issues/${pr_number}/comments" \
    --jq ".[] | select(.body | contains(\"${marker}\")) | .id" 2>/dev/null | head -1 || true)

  if [[ -n "$existing_comment_id" ]]; then
    gh_retry gh api "repos/${owner}/${repo}/issues/comments/${existing_comment_id}" \
      -X PATCH -f body="$body" > /dev/null 2>&1 || true
  else
    gh_retry gh pr comment "$pr_number" --repo "${owner}/${repo}" --body "$body" > /dev/null 2>&1 || true
  fi
}

# ===========================================================================
# Execution Modes
# ===========================================================================
run_periodic() {
  echo "[periodic] Starting periodic PR agent run"

  discover_oape_prs

  local pr_count
  pr_count=$(wc -l < "$PR_LIST_FILE" 2>/dev/null || echo 0)
  pr_count=$((pr_count))  # trim whitespace

  if [[ "$pr_count" -eq 0 ]]; then
    echo "[periodic] No open PRs found, nothing to do"
    return 0
  fi

  local max_prs="$PR_AGENT_MAX_PRS"
  local processed=0

  while IFS= read -r pr_url; do
    [[ -z "$pr_url" ]] && continue

    if [[ "$processed" -ge "$max_prs" ]]; then
      echo "[periodic] Reached max PRs (${max_prs}), stopping"
      break
    fi

    echo "[periodic] Processing PR $((processed + 1))/${max_prs}: ${pr_url}"

    # Build flags for the subprocess invocation
    local -a flags=()
    [[ "$DRY_RUN" == "true" ]] && flags+=(--dry-run)
    [[ "$MONITOR_ONLY" == "true" ]] && flags+=(--monitor-only)
    [[ "$REVIEW_HANDLER_ENABLED" == "true" ]] && flags+=(--review)

    # Invoke entrypoint.sh as a subprocess per PR, wrapped in timeout.
    # Each PR gets its own process for isolation — a crash or hang in one
    # does not affect subsequent PRs.
    local timeout_rc=0
    timeout --signal=TERM --kill-after=30 "$PR_TIMEOUT_SECONDS" \
      "${BASH_SOURCE[0]}" --mode on-demand --pr-url "$pr_url" "${flags[@]}" \
      || timeout_rc=$?

    if [[ "$timeout_rc" -eq 124 ]]; then
      echo "[periodic] PR ${pr_url} — timed out after ${PR_TIMEOUT_SECONDS}s"
      parse_pr_url "$pr_url"
      _post_timeout_report "$OWNER" "$REPO" "$PR_NUMBER"
      audit_log "error" "" "" "" "timeout after ${PR_TIMEOUT_SECONDS}s for ${pr_url}"
    elif [[ "$timeout_rc" -ne 0 ]]; then
      echo "[periodic] PR ${pr_url} — failed (exit ${timeout_rc}, continuing)"
      audit_log "error" "" "" "" "process_pr failed (exit ${timeout_rc}) for ${pr_url}"
    else
      echo "[periodic] PR ${pr_url} — completed successfully"
    fi

    processed=$((processed + 1))

    # Rate limit between PRs
    if [[ "$processed" -lt "$max_prs" ]] && [[ "$processed" -lt "$pr_count" ]]; then
      echo "[periodic] Waiting ${RATE_LIMIT_SECONDS}s before next PR..."
      sleep "$RATE_LIMIT_SECONDS"
    fi
  done < "$PR_LIST_FILE"

  echo "[periodic] Processed ${processed} PR(s)"
}

run_on_demand() {
  # Timeout is handled by the outer caller (Prow job timeout, user) for single-PR mode.
  local pr_url="$1"
  echo "[on-demand] Processing single PR: ${pr_url}"

  parse_pr_url "$pr_url"
  validate_repo_allowed "$OWNER" "$REPO"

  process_pr "$pr_url"
  echo "[on-demand] Done"
}

# ===========================================================================
# Main
# ===========================================================================
main() {
  echo "============================================"
  echo "  OAPE PR Lifecycle Agent — Phase 1 MVP"
  echo "  Mode: ${MODE}"
  echo "  Monitor Only: ${MONITOR_ONLY}"
  echo "  Dry Run: ${DRY_RUN}"
  echo "  Time: $(date -u +"%Y-%m-%d %H:%M UTC")"
  echo "============================================"

  run_prechecks

  case "$MODE" in
    periodic)
      run_periodic
      ;;
    on-demand)
      run_on_demand "$PR_URL_ARG"
      ;;
    *)
      echo "ERROR: Unknown mode: ${MODE} (expected 'periodic' or 'on-demand')" >&2
      exit 1
      ;;
  esac

  echo "[main] PR agent run complete"
}

# Only run main when executed directly (not sourced for timeout subprocess)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main
fi
